app:
  build: .
  ports:
   - "8080:80"
  volumes:
   - ./:/var/www/public
   #- .nginx:/etc/nginx/conf.d
  #entrypoint: ["composer install --no-dev", "composer dump-autoload --optimize --no-dev"]
  links:
   - db

db:
  image: mysql:5.7
  ports:
  - "3308:3306"
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: teste
  volumes:
    - ./.data:/var/lib/mysql